language: android
dist: trusty

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew assembleDebug
  - ./gradlew testDebugUnitTest